config/routes.rb
WarhammerBuilder::Application.routes.draw do

  devise_for :users
  root to: 'armies#index'

  get "armies/new_blood" => "armies#new_blood"
  get "armies/new_wolf" => "armies#new_wolf"
  get "armies/new_ork" => "armies#new_ork"
  get "armies/new_ultra" => "armies#new_ultra"
  get "armies/new_dark" => "armies#new_dark"
  match '/dashboard' => 'users#dashboard'

  resources :armies do
    resources :squads
  end

  resources :squads, only: [] do
    resources :troops
  end



end

app/models/army.rb
class Army < ActiveRecord::Base
  attr_accessible :faction, :name, :squads_attributes, :extra, :profile_id
  belongs_to :profile
  has_many :squads
  accepts_nested_attributes_for :squads, allow_destroy: true
  validates_presence_of :name

  FACTIONS = [
    "Choas Force",
    "Blood Marine",
    "Dark Angel"
  ]

  def points
    points = 0
    squads.each do |squad|
      points += squad.points
    end
    points
  end


end

app/models/havoc.rb
class Havoc < Troop

  def self.create
    Havoc.new(points: 13, weapon: :meltagun)
  end
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  attr_accessible :name, :user_id, :armies_attributes
  belongs_to :user
	has_many :armies
 	accepts_nested_attributes_for :armies, allow_destroy: true

end

app/models/squad.rb
class Squad < ActiveRecord::Base
  attr_accessible :army_id, :name, :points, :size, :troops_attributes
  belongs_to :army
  has_many :troops
  accepts_nested_attributes_for :troops, allow_destroy: true
  validates_presence_of :name
  after_create :delete_invalid_squad
  
  TYPES = {}

  def count_size
    troops.size
  end

  def delete_invalid_squad
    self.delete unless valid_squad?(self.name)
  end

  def name_troop
    self.troops.each do |troop|
    troop.name = 8
    end 
  end

  private

  def valid_squad?(squad) 
    ["Cultist", "Thousand Son", "Havoc", "Marine", "Berzerker", "LandRaider", "Sorcerer", "Kharn", "Terminator", "Deamon Prince",
      "Choas Biker", "Raptor", "Warp Talon", "Tactical", "Scout", "Biker", "WarBoss", "Zogwort", "Weirdboy",
      "Land Speeder", "Stern Guard", "Devastator", "Dante", "Mephiston", "Libarian", "Ork", "Gretchin", "Big Gunz",
      "BattleWagon", "Looted Wagon", "StormBoyz", "Ork Bike", "War Buggy", "TankBustas", "Lootas", "Kommandos", "WarBoss",
      "Zogwort", "Weirdboy", "Great Wolf", "Wolf Lord", "SkyClaw", "Wolfpack", "Lone Wolf", "Wolf Guard", "Blood Claw", "Long Fang", "Grey Hunter", 
      "Wolf Priest"  ].include?(squad)
  end
  
end

app/models/troop.rb
class Troop < ActiveRecord::Base
  attr_accessible :name, :points, :squad_id, :weapon, :side_weapon, :addons
  belongs_to :squad
  after_create :name_troop

  def name_troop
  	self.name = 8
  end
end

app/models/user.rb
class User < ActiveRecord::Base

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  attr_accessible :email, :password, :password_confirmation, :remember_me, :profile_attributes

  has_one :profile, dependent: :destroy
  accepts_nested_attributes_for :profile

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/armies_controller.rb
class ArmiesController < ApplicationController

  def index
    @armies = Army.all
  end

  def show
    @army = Army.find(params[:id])
  end

  def new_blood
    @army = Army.new
    @squad = @army.squads.build
    @squad.troops.build
  end

  def new_ultra
    @army = Army.new
    @squad = @army.squads.build
    @squad.troops.build
  end

  def new_dark
    @army = Army.new
    @squad = @army.squads.build
    @squad.troops.build
  end

  def new_wolf
    @army = Army.new
    @squad = @army.squads.build
    @squad.troops.build
  end

  def new_ork
    @army = Army.new
    @squad = @army.squads.build
    @squad.troops.build
  end


  def new
    @army = Army.new
    @squad = @army.squads.build
    @squad.troops.build
  end

  def edit
    @army = Army.find(params[:id])
    @name_number = 1
    squad = @army.squads.build
    squad.troops.build
  end

  def create
    @army = Army.new(params[:army])
    @user = current_user
    @profile = @user.profile if @user != nil
    if @army.save
      if @profile != nil
        @profile.armies << @army
          redirect_to dashboard_path
      else
        redirect_to @army, notice: 'Army was successfully created.'
      end
    else
      render :new
    end
  end

  def update
    @army = Army.find(params[:id])

    if @army.update_attributes(params[:army])

      redirect_to @army, notice: 'Army was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @army = Army.find(params[:id])
    @army.destroy
    @user = current_user
    @profile = @user.profile
    if @profile != nil
      redirect_to dashboard_path
    else
      redirect_to root_path
    end
  end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
end

app/controllers/squads_controller.rb
class SquadsController < ApplicationController

  before_filter :fetch_army
  def index
    @squads = Squad.all
  end

  def show
    @squad = Squad.find(params[:id])
  end

  def new
    @squad = Squad.new
    troop = @squad.troops.build
  end

  def edit
    @squad = Squad.find(params[:id])
  end

  def create
    @squad = Squad.new(params[:squad])
    if @squad.save
      redirect_to @squad, notice: 'Squad was successfully created.'
    else
      render :new
    end
  end

  def update
    @squad = Squad.find(params[:id])

    if @squad.update_attributes(params[:squad])
      redirect_to @army, notice: 'Squad was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @squad = Squad.find(params[:id])
    @squad.destroy
  end

  private

  def fetch_army
    @army = Army.find(params[:army_id])
  end

end

app/controllers/troop_controller.rb
class TroopController < ApplicationController

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def dashboard
  
    @user = current_user
    @profile = @user.profile
    @armies = @profile.armies
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  # def link_to_add_fields(name, f, association)
  #   new_object = f.object.class.reflect_on_association(association).klass.new
  #   fields = f.fields_for(association, new_object, :child_index => "new_#{association}") do |builder|
  #     render(association.to_s.singularize + "_fields", :f => builder)
  #   end
  #   link_to_function(name, h("add_fields(this, \"#{association}\", \"#{escape_javascript(fields)}\")"))
  # end
end

app/views/armies/_form.html.haml
= simple_form_for @army do |f|
  .faction= f.input :faction, label: false
  .rank
  .name
    Army Name
    .comander_name= f.input :name, label: false
    
  .army_points
  .progressbar
    .bar
      .barpoints 0%
  .squadform
    .army_list
      %table
        %thead
          %th Squads
          %th #
          %th.points points
          %th max
        %tr
          %td HQ
          %td.hq 0
          %td.hqpoints 0
          %td 2
        %tr
          %td Troop
          %td.troop 0
          %td.trooppoints 0
          %td 6
        %tr
          %td Elite
          %td.elite 0
          %td.elitepoints 0
          %td 3
        %tr
          %td Heavy Support
          %td.heavy 0
          %td.heavypoints 0
          %td 3
        %tr
          %td Fast Attack
          %td.fast 0
          %td.fastpoints 0
          %td 3
        %tr
          %td Total
          %td.total 0
          %td 0
          %td 18

    %h3
    = f.simple_fields_for :squads do |squad|
      .fields.squad
        = squad.input :name, label: false, collection: Squad::TYPES.to_a, prompt: "Select squad"
        .squad_wrap
          = link_to "Remove", '#', class: "remove_squad"
          %table.squad_table
            %thead
              = squad.input :points, label: false

              %th.squad_details
                .squadtype
                %table.chart
                  %tr.chart
                    %td Points 
                    %td Size
                    %td Type
                  %tr.chart_stats
                    %td
                      .squadpoints
                    %td
                      .squadsize
                    %td
                      .squadtype

            %tbody
              = squad.simple_fields_for :troops do |troop|
                %tr.troop
                  %td
                    .troop_points
                    .troop_icon
                    = troop.input :weapon, collection: ["Select Weapon"], prompt: "Select Weapon", label: false
                    = troop.input :side_weapon, collection: ["Select Weapon"], prompt: "Select Weapon", label: false
                    = link_to "remove", "#", class: "remove_troop"
                    %table.troop_stat
                      %tr
                        %td WS
                        %td BS
                        %td S
                        %td T
                        %td W
                        %td I
                        %td A
                        %td LD
                        %td SV
                      %tr
                        %td 1
                        %td 1
                        %td 1
                        %td 1
                        %td 1
                        %td 1
                        %td 1
                        %td 1
                        %td 1


          = link_to "Add Troop", "#", class: "add_troop"
    .add_buttons
      = link_to "Add Troop Squad", '#', id: "add_squad"
      = link_to "Add Elite Squad", '#', id: "add_elite"
      = link_to "Add Heavy Support", '#', id: "add_heavyweapon"
      = link_to "Add Fast Attack", '#', id: "add_fastattack"
      = link_to "Add HQ", '#', id: "add_hq"

    .create_army= f.button :submit

app/views/armies/edit.html.haml
%h1 Edit Your Army

= render 'form'

= link_to 'Show', @army
\|
= link_to 'Back', armies_path

app/views/armies/index.html.haml
%html

  %body.index
    %head
      %h1
        = image_tag("indextitle.png")
      %p.intro Warhammer 40K Army Builder is a web application that creates Warhammer armies using click and select features create a user friendly app that condenses game rules in the browser.
      %ul.index
        %li
          = link_to 'Chaos Army', new_army_path, class: "Choas_Army_Button"
          %ul.dropdown
            .box_pic= link_to image_tag("listchaos.jpeg"), new_army_path
            .box_pic2= link_to image_tag("listchaos.jpeg"), new_army_path
            %p.chaos
              The Chaos Space Marines, also sometimes called a Traitor Marine or a Renegade Marine, is a former Loyalist Space Marine of the Imperium of Man who has chosen to betray the service of the Emperor of Mankind and dedicate his soul to the service of Chaos and its foul deities. Such corrupt Astartes normally belong to one of the 9 Traitor Legions that betrayed the Emperor during the ancient civil war called the Horus Heresy more than 10,000 standard years ago, while others come from Space Marine Chapters created long after the Heresy ended that have turned Renegade.
        %li
          = link_to 'Blood Angel Army', armies_new_blood_path, class: "BloodAngel_Army_Button"
          %ul.dropdown
            .box_pic=link_to image_tag("blooddrop.png"), armies_new_blood_path
            .box_pic2=link_to image_tag("blooddrop.png"), armies_new_blood_path
            %p.blood
              The Blood Angels are one of the 20 First Founding Legions of the Space Marines and were originally the IX Legion before the Second Founding broke the Legiones Astartes up into 1000 separate Chapters. They are well-known across the galaxy for their bloodthirsty nature in battle, and feared for the curse of flawed gene-seed they carry. The Blood Angels are amongst the longest-lived of the Adeptus Astartes, with some of the Chapter's Space Marines having served the Emperor of Mankind for over a thousand standard years. Thanks to recent events, the Blood Angels' numbers have been severely depleted.
        %li
          = link_to 'Space Wolf Army', armies_new_wolf_path, class: "SpaceWolf_Army_Button"
          %ul.dropdown
            .box_pic=link_to image_tag("wolfdrop.jpg"), armies_new_wolf_path
            .box_pic2=link_to image_tag("wolfdrop.jpg"), armies_new_wolf_path
            %p.wolf
              The Space Wolves are one of the original 20 First Founding Space Marine Legions. Once the VI Legion of Astartes raised by the Emperor at the dawn of the Great Crusade, the Space Wolves are renowned for their anti-authoritarian ways and their embrace of their homeworld Fenris' savage barbarian culture as well as their extreme deviation from the Codex Astartes in the Chapter's organisation. After the Horus Heresy and the resultant Second Founding reforms of the Adeptus Astartes, the Space Wolves Legion was divided into two Chapters.
        %li
          = link_to 'Dark Angel Army', armies_new_dark_path, class: "DarkAngel_Army_Button"
          %ul.dropdown
            .box_pic=link_to image_tag("dropdark.jpeg"), armies_new_dark_path
            .box_pic2=link_to image_tag("dropdark.jpeg"), armies_new_dark_path
            %p.dark
              The Dark Angels are considered amongst the most powerful and secretive of the Loyalist Space Marine Chapters. They were the I Legion of the original 20 Space Marine Legions to be created during the First Founding of the 30th Millennium. Though they claim complete allegiance and service to the Emperor of Mankind, their actions and secret goals at times seem at odds with that professed loyalty, as the Dark Angels strive above all other things to atone for an ancient crime of betrayal committed over 10,000 standard years ago against the trust of the Emperor during the time of the Great Crusade and the Horus Heresy.
        %li
          = link_to 'Ultra Marine Army', armies_new_ultra_path, class: "Ultra_Army_Button"
          %ul.dropdown
            .box_pic=link_to image_tag("dropultra.jpeg"), armies_new_ultra_path
            .box_pic2=link_to image_tag("dropultra.jpeg"), armies_new_ultra_path
            %p.ultra
              The Ultramarines are considered one of the strongest and most honoured of all the Space Marine Chapters in the Imperium of Man, and were responsible for almost single-handedly holding the Imperium together after the Horus Heresy. Highly disciplined and courageous warriors, the Ultramarines have remained true to the teachings of their Primarch Roboute Guilliman for 10,000 standard years. The Ultramarines were originally the XIII Space Marine Legion before the reforms that initiated the Second Founding and reshaped the Imperium after the Heresy on the orders of Guilliman himself.

        %li
          = link_to 'Ork Army', armies_new_ork_path, class: "Ork_Army_Button"
          %ul.dropdown
            .box_pic=link_to image_tag("dropork.jpg"), armies_new_ork_path
            .box_pic2=link_to image_tag("dropork.jpg"), armies_new_ork_path
            %p.ork
              The Orks, also called Greenskins, are a savage, warlike, green-skinned race of humanoids who are spread all across the Milky Way Galaxy. They are seen by their enemies as savage, warlike, and crude, but they are the most successful species in the whole galaxy, outnumbering possibly every other intelligent race, even Mankind. However, this massive population of Orks is split into hundreds of tiny empires, often warring between themselves. It has been speculated that were the Orks ever to unite as a single racial entity, they would undoubtedly crush any opposition that would dare to stand against such a tsunami of green muscle.

app/views/armies/new.html.haml
%html

  %body.choasbackground
    %h1 Chaos

    = render 'form'

app/views/armies/new_blood.html.haml
%html

  %body.bloodangelbackground
    %h1 Blood Angel

    = render 'form'

app/views/armies/new_choas.html.haml
%html

  %body.choasbackground
    %h1 Choas

    = render 'form'

app/views/armies/new_dark.html.haml
%html

  %body.darkbackground
    %h1 Dark Angel

    = render 'form'

app/views/armies/new_ork.html.haml
%html

  / = javascript_include_tag "ork"

  %body.orkbackground
    %h1 Ork

    = render 'form'

app/views/armies/new_ultra.html.haml
%html

  %body.ultrabackground
    %h1 Ultra Marine

    = render 'form'

app/views/armies/new_wolf.html.haml
%html

  %body.spacewolfbackground
    %h1 Space Wolf

    = render 'form'

app/views/armies/show.html.haml
%p#notice= notice
  
-if user_signed_in?
  %p View Armies
-else
  %p You must be Loged in to Save an Army
  = link_to "Sign up", new_user_registration_path
%p
  %b Name:
  = @army.name
  = @army.faction
%p

%table.show
  %tr
    %th Squad
    %th Points
    %th Size
  - @army.squads.each do |squad|
    %tr
    %td=link_to "#{squad.name}", army_squad_path(@army, squad)
    %td= squad.points
    %td= squad.count_size

= link_to 'Edit', edit_army_path(@army)
\|
= link_to 'Back', armies_path

app/views/layouts/application.html.haml
%head
  %title WarhammerBuilder
  = stylesheet_link_tag    "application", :media => "all"
  = javascript_include_tag "application"
  = csrf_meta_tags
%body
  %nav
    -if user_signed_in?
      = link_to "Log Out", destroy_user_session_path, method: :delete
      = link_to "My Profile", dashboard_path

    -else
      = link_to "Login", new_user_session_path
      = link_to "Sign up", new_user_registration_path

  %div#pagewrap
    = yield

app/views/squads/edit.html.haml
%h1= "#{@squad.name}"

.squad_edit
%p Size
= @squad.troops.size
%p Points
= @squad.points


= simple_form_for [@army, @squad] do |f|
  = f.simple_fields_for :troops do |troop|
    = troop.input :weapon
    = troop.input :side_weapon

  = f.button :submit
%p Names

app/views/squads/index.html.haml
%h1 Listing squads

%table
  %tr
    %th Name
    %th Points
    %th Size
    %th Army
    %th
    %th
    %th

  - @squads.each do |squad|
    %tr
      %td= squad.name
      %td= squad.points
      %td= squad.size
      %td= squad.army_id
      %td= link_to 'Edit', edit_army_squad_path(@army, squad)
      %td= link_to 'Destroy', army_squad_path(@army, squad), :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Squad', new_army_squad_path(@army)

app/views/squads/new.html.haml
%h1 New Troop for Squad
= simple_form_for [@army, @squad] do |f|
  = f.simple_fields_for :troops do |troop|
    = troop.input :name
  = f.submit
%p= @army.squads
- m = @army.squads.last
= m.troops

app/views/squads/show.html.haml
%p#notice= notice
%p
	%b Name:
	= @squad.name
%p
	%b Points:
	= @squad.points
%p
	- @squad.troops.each do |troop|
		%p 
			troop
			= troop.weapon
			= troop.side_weapon
			= troop.name

app/views/users/dashboard.html.haml
%h1 Armies

= @profile.name

%h2 Armies

%table
  %thead
    %tr
      %th Name
      %th Faction
      %th.action Edit 
      %th.action Destroy
      %th Points
  %tbody
    - @armies.each do |army|
      %tr
        %td= link_to army.name, army
        %td= army.faction
        %td= link_to 'Edit', edit_army_path(army)
        %td= link_to 'Destroy', army, method: :delete, data: { confirm: 'Are you sure?' }
        %td= army.points
        
= link_to "New Army", armies_path

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>